[workspace]
members = [
    "bbl-bind",
    "bbl-clang",
    "bbl-extract",
    "bbl-scan",
    "bbl-translate",
    "bbl-write",
    "bbl",
    "bbl-gen",
    "bbl-dumpast",
    "bbl-util",
    "examples/*",
]
