[package]
name = "clangsystest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clang-sys = { path = "../clang-sys", features=["clang_13_0"] }
env_logger = "0.9.0"
log = "0.4.17"
